### ISSUE TITLE
Unable to detect change from the outside

### ISSUE THREAD

**Issue by kolaente** [NikulinIlya/vue-easymde#3]
Whenever I change a value which I bound with `v-model` to an instance of vue-easymde and change it from the outside, it does not update inside of it.

This seems to be fixed in https://github.com/F-loat/vue-simplemde.

**Comment by NikulinIlya** [comment]
I believe that recent updates made depending on F-loat/vue-simplemde should solve this problem.

**Comment by kolaente** [comment]
Just tested it with the new version, does not seem to fix that particular bug.

**Comment by evanre** [comment]
Just faced with this issue. It seems that two-way binding feature explicitly closed here
`vue-easymde/src/index.vue`
```watch: {
  value(val) {
    if (this.isValueUpdateFromInner) {
      this.isValueUpdateFromInner = false;
    } else {
      this.easymde.value(val);
    }
  },
},```

Hi, @NikulinIlya why do we need this `isValueUpdateFromInner` check?

**Comment by suxur** [comment]
Make sure you're using `v-model` instead of the `value` prop.

`<vue-easymde v-model="your_value" />`

This worked for me.

**Comment by JuliusJacobitz** [comment]
any updates on this?

I have a similar issue: If the v-model updates to an empty string, the change does not get detected. @NikulinIlya
